
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author csarm
 */
public class VerificadorPrecio extends javax.swing.JFrame {
    String codigo = "";
            String[][] productos = new String[][]
            {
                { "1", "PINTURA BEREL VINIL ACRÍLICA BASE NEUTRA 19 L", "$2,195.00", "berel19l.jpg", "Pintura base neutra Berelinte Berel de 19 L, brinda un recubrimiento para superficies de yeso, cemento, mortero, entre otros; tanto en interiores como en exteriores. Hecha con vinil y acrílico que le brinda resistencia al lavado y dura hasta 7 años."},
                { "2", "PINTURA BEHR PREMIUM PLUS MATE BASE BLANCO ULTRA PURO 18.9 L", "$3,945.00", "BEHR.jpg","Pintura 100% acrílica Behr Premium Plus, entintable en colores claros, brinda un recubrimiento especial para superficies exteriores como revestimiento de madera, vinilo y de fibra de cemento como mortero, ladrillo, mampostería y enrejado; dejando en ellas un acabado mate, ideal para disimular imperfecciones. Su fórmula ecológica, tiene cero niveles de COV y bajo olor, es resistente a la humedad y rayos UV, además de ser lavable con agua y jabón. Cuenta con secado rápido 2 horas al tacto. Su presentación es en cubeta de 18.9 L que brinda un rendimiento de 116 a 186 m2 con excelente cobertura. Para su aplicación con brocha o rodillo se debe utilizar directamente, sin diluir."},
                { "3", "SELLADOR VINÍLICO 19 L", "$1,529.00", "sellador.jpg","Sellador vinílico 570 Berel. Diseñado especialmente para uso interior en aplanados de yeso, cemento o mortero que serán pintados por pinturas emulsionadas de cualquier tipo; su secado al tacto es de 1 hora. Su fórmula elaborada con resinas de alta calidad vinilacrílicas brinda gran adhesión, resistencia a la humedad y sellado, la mezcla diluida rinde de 3 a 5m2/L. Presentación en cubeta de 19 L."},
                { "4", "PISTOLA ELÉCTRICA DE 900 ML NEGRO MASTER HARDWARE", "$1,129.00", "pistola.jpg","La Pistola Eléctrica Master Hardware con capacidad de 900 mililitros permite realizar trabajos de pintura con excelente calidad y acabados. Se puede emplear con todo tipo de pinturas y sobre cualquier material, trabajando tanto en interior como exterior, cuenta con ajuste de aire, volumen y abanico para adaptarse a las necesidades del usuario. Ahorra tiempo y pintura cada vez que se utiliza, gracias a su potencia de 450 W que permite pintar a una distancia de hasta 5 metros en sólo 5 minutos."},
                { "5", "KIT SEMIPROFESIONAL DE PLÁSTICO DE 39.5 X 29 X 6.5", "$185.00", "kit.jpg","Kit semiprofesional HDX con 5 piezas, útil para realizar tareas de mantenimiento y decoración sobre los muros del hogar. Cuenta con 1 charola para cargar los rodillos y dosificar la pintura evitando desperdicios de 39.5 x 29 x 6.5 cm, 1 brocha de poliéster de 2-1/2 pulgadas (6.3 cm) y 1 maneral semiprofesional de 9-1/2 pulgadas (24.1 cm) con mango de plástico negro. Además, 2 felpas de uso general, la primera de 3/4 de pulgada (1.9 cm) para superficies rugosas y la segunda de 3/8 de pulgada (0.9 cm) para superficies lisas."}
            };
            

    /**
     * Creates new form VerificadorPrecio
     */
    public VerificadorPrecio() {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        System.out.println(size);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height);
        setResizable(false);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //System.out.println(evt.getKeyChar());
        if (evt.getKeyCode() != 10) {
            codigo += evt.getKeyChar();
        }
        else
        {
            System.out.println(codigo);
            //Buscamos producto
            for (int i = 0; i < 5; i++)
                {
                     System.out.println(productos[i][0]);
                    if (codigo.equals(productos[i][0]))
                    {
                         System.out.println(productos[i][1]);
                        //MessageBox.Show("Productos" + productos[i, 1] + productos[i, 2]);
                        jLabel1.setVisible(true);
                        jLabel2.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel1.setText(productos[i][1]);
                        jLabel2.setText(productos[i][2]);
                        jLabel3.setText(productos[i][4]);
                         
                        ImageIcon imgThisImg = new ImageIcon(".\\img\\" + productos[i][3]);
                        jLabel4.setIcon(imgThisImg);

                        //pictureBox1.Location = new Point(200,
               //this.Height / 2 - pictureBox1.Height / 2);

                        //productFound = true;
                    }
                }

                codigo = "";

                //if (!productFound)
                //{
                    //pictureBox1.Image = Image.FromFile(ruta + @"\codigo-de-barras-creativos-png.jpg");
                    //ini();
                    //MessageBox.Show("Producto no encontrado favor de acudir con algun empleado");
                //}
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificadorPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificadorPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificadorPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificadorPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerificadorPrecio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
